### ISSUE TITLE
Server Viewer Does Not Work Anymore

### ISSUE THREAD

**Issue by mirrox1337** [Wruczek/ts-website#5]
My Server Viewer Worked When first Got This Website. Now I get "An error occured! 0: connection to server 'ts3.***********.tk:10011' lost" and everything else works
![screenshot_1](https://cloud.githubusercontent.com/assets/14304552/18073595/a6bb52a6-6e67-11e6-83f4-ae1a511ccc5c.png)

**I have Enabled Mod_rewrite and elso enabled .htaccess and enabled additional website features
What Should I Do?**

**Comment by Wruczek** [comment]
If it worked previously, then it's likely a problem with your web server or TeamSpeak server.
Did other parts of website (such as Server Status, Admin List) work fine?

**Comment by mirrox1337** [comment]
Yes everything else works as it should

**Comment by mirrox1337** [comment]
I solved the problem kind of.
when I host my TS3 Server From Windows everything works but it does not on ubuntu?

**Comment by Wruczek** [comment]
Are you hosting both Teamspeak and website on the same server?

**Comment by mirrox1337** [comment]
nope

**Comment by Wruczek** [comment]
The issue is on your side, it's not website's fault. It will be hard to help you.
Are you sure that ports are open on the both webserver and teamspeak server? If you are using website hosting service, try contacting support for help. If you are using free website hosting service, then keep in mind that most of them have serious problems with websites like this.
